### ISSUE TITLE
输入的信息过多

### ISSUE THREAD

**Issue by LEDZB** [muziing/NetAssist_PyQt#1]
您好，我想请问一下为何我在设置完之后会提示输入的信息过多呢

**Comment by muziing** [comment]
https://muzing.top/posts/5ab16c09/#%E7%94%A8%E6%88%B7%E8%BE%93%E5%85%A5%E6%A3%80%E6%9F%A5

博文中关于此内容已有详细的说明、代码对照讲解。

**Comment by LEDZB** [comment]
> https://muzing.top/posts/5ab16c09/#%E7%94%A8%E6%88%B7%E8%BE%93%E5%85%A5%E6%A3%80%E6%9F%A5
> 
> 博文中关于此内容已有详细的说明、代码对照讲解。

好的，非常感谢您的帮助，已经成功了

**Comment by LEDZB** [comment]
另外我想请问一下我只是想在一个界面显示收到的udp数据，那么这个应该怎么做呢
